

database_path = './app/storage/database.db'


upload_folder = "videos"
allowed_extensions = ["mp4", "avi", "mov"]


rtp_port = 8000
rtp_path = "picam/stream"


log_level = "DEBUG"
log_format = "%(asctime)s - %(levelname)s - %(message)s"


server_port = 5000
server_host = "0.0.0.0"

